FROM python:3.10-slim-bookworm
COPY --from=ghcr.io/astral-sh/uv:0.6.14 /uv /uvx /bin/

# RUN uv pip install \
#   dagster \
#   dagster-docker \
#   --system

WORKDIR /opt/dagster/app

COPY imgw /opt/dagster/app/imgw
COPY pyproject.toml /opt/dagster/app/pyproject.toml
COPY uv.lock /opt/dagster/app/uv.lock

RUN uv sync --frozen --all-extras

ENV VIRTUAL_ENV=/opt/dagster/app/.venv \
  PATH="/opt/dagster/app/.venv/bin:$PATH" \
  DAGSTER_CURRENT_IMAGE='imgw:0.0.1-dagster'

EXPOSE 4000

ENTRYPOINT ["uv", "run", "dagster", "code-server", "start", "-h", "0.0.0.0", "-p", "4000", "-m", "imgw.dags.dagster.definitions"]

CMD []
